---
abstract: 'rest-client => Test automation tool for restful web services'
author:
  - 'Mithun Radhakrishnan <rkmithun@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4206, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: APP-REST-RestTestSuite
provides:
  APP::REST::ParallelMyUA:
    file: lib/APP/REST/ParallelMyUA.pm
    version: 0.01
  APP::REST::RestTestSuite:
    file: lib/APP/REST/RestTestSuite.pm
    version: 0.02
requires:
  File::Basename: 0
  File::Path: 0
  Getopt::Long: 0
  HTTP::Request: 0
  LWP::Parallel::UserAgent: 0
  LWP::UserAgent: 0
  Time::HiRes: 0
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: 0.02
